//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiaoHangEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public int MaDonHang { get; set; }
        public string TenDonHang { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayGiaoDuKien { get; set; }
        public Nullable<int> GiaTriDonHang { get; set; }
        public Nullable<int> ThuHo { get; set; }
    
        public virtual CHITIETDONHANG CHITIETDONHANG { get; set; }
    }
}
